name: switchScript

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

env:
  SCRIPT_SH: switchScript.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt install -y jq

    - name: "Build & Release"
      run: |
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "tag_name=$(date +%Y%m%d)" >> $GITHUB_ENV
        chmod +x $SCRIPT_SH
        ./$SCRIPT_SH
        zip -rq SwitchSD.zip SwitchSD
      env:
        GH_TOKEN: ${{ secrets.PAT }}

    - name: Read description.txt
      id: description
      uses: juliangruber/read-file-action@v1
      with:
        path: ./description.txt

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} ❤️ | 大气层个人整合包
        allowUpdates: true
        tag: ${{ env.tag_name }}
        commit: main
        body: "${{ steps.description.outputs.content }}"
        artifacts: "SwitchSD.zip"

    - name: Delete workflow runs for current repo
      uses: Mattraks/delete-workflow-runs@v2
      with:
        repository: ${{ github.repository }}
        retain_days: 7
        keep_minimum_runs: 6